"groups":
- "name": "external-secrets-operator"
  "rules":
  - "alert": "ExternalSecretsSyncErrors"
    "annotations":
      "dashboard_url": "https://grafana.com/d/eso-resources-skj2/eso-resources?var-namespace={{ $labels.exported_namespace }}&var-name={{ $labels.name }}"
      "description": "More than 5% of sync calls failed for ExternalSecret {{ $labels.name }} in {{ $labels.exported_namespace }} the past 15m."
      "summary": "External Secrets Operator has a high ExternalSecret sync error rate."
    "expr": |
      (
        sum(
          increase(
            externalsecret_sync_calls_error{
              job=~".*external-secrets.*"
            }[15m]
          )
        ) by (exported_namespace, name)
        /
        sum(
          increase(
            externalsecret_sync_calls_total{
              job=~".*external-secrets.*"
            }[15m]
          )
        ) by (exported_namespace, name)
        * 100
      ) > 5
    "for": "5m"
    "labels":
      "severity": "warning"
  - "alert": "ExternalSecretsExternalSecretNotReady"
    "annotations":
      "dashboard_url": "https://grafana.com/d/eso-resources-skj2/eso-resources?var-namespace={{ $labels.exported_namespace }}&var-name={{ $labels.name }}"
      "description": "ExternalSecret {{ $labels.name }} in {{ $labels.exported_namespace }} has not been Ready for the past 15m."
      "summary": "External Secrets Operator ExternalSecret is not ready."
    "expr": |
      sum(
        externalsecret_status_condition{
          job=~".*external-secrets.*",
          condition="Ready",
          status="False"
        }
      ) by (exported_namespace, name, condition, status)
      == 1
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "ExternalSecretsClusterExternalSecretNotReady"
    "annotations":
      "dashboard_url": "https://grafana.com/d/eso-resources-skj2/eso-resources?var-name={{ $labels.name }}"
      "description": "ClusterExternalSecret {{ $labels.name }} has not been Ready for the past 15m."
      "summary": "External Secrets Operator ClusterExternalSecret is not ready."
    "expr": |
      sum(
        clusterexternalsecret_status_condition{
          job=~".*external-secrets.*",
          condition="Ready",
          status="False"
        }
      ) by (name, condition, status)
      == 1
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "ExternalSecretsSecretStoreNotReady"
    "annotations":
      "dashboard_url": "https://grafana.com/d/eso-resources-skj2/eso-resources?var-namespace={{ $labels.exported_namespace }}&var-secret_store_name={{ $labels.name }}"
      "description": "SecretStore {{ $labels.name }} in {{ $labels.exported_namespace }} has not been Ready for the past 15m."
      "summary": "External Secrets Operator SecretStore is not ready."
    "expr": |
      sum(
        secretstore_status_condition{
          job=~".*external-secrets.*",
          condition="Ready",
          status="False"
        }
      ) by (exported_namespace, name, condition, status)
      == 1
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "ExternalSecretsClusterSecretStoreNotReady"
    "annotations":
      "dashboard_url": "https://grafana.com/d/eso-resources-skj2/eso-resources?var-secret_store_name={{ $labels.name }}"
      "description": "ClusterSecretStore {{ $labels.name }} has not been Ready for the past 15m."
      "summary": "External Secrets Operator ClusterSecretStore is not ready."
    "expr": |
      sum(
        clustersecretstore_status_condition{
          job=~".*external-secrets.*",
          condition="Ready",
          status="False"
        }
      ) by (name, condition, status)
      == 1
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "ExternalSecretsPushSecretNotReady"
    "annotations":
      "dashboard_url": "https://grafana.com/d/eso-resources-skj2/eso-resources?var-namespace={{ $labels.exported_namespace }}&var-push_secret_name={{ $labels.name }}"
      "description": "PushSecret {{ $labels.name }} in {{ $labels.exported_namespace }} has not been Ready for the past 15m."
      "summary": "External Secrets Operator PushSecret is not ready."
    "expr": |
      sum(
        pushsecret_status_condition{
          job=~".*external-secrets.*",
          condition="Ready",
          status="False"
        }
      ) by (exported_namespace, name, condition, status)
      == 1
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "ExternalSecretsClusterPushSecretNotReady"
    "annotations":
      "dashboard_url": "https://grafana.com/d/eso-resources-skj2/eso-resources?var-push_secret_name={{ $labels.name }}"
      "description": "ClusterPushSecret {{ $labels.name }} has not been Ready for the past 15m."
      "summary": "External Secrets Operator ClusterPushSecret is not ready."
    "expr": |
      sum(
        clusterpushsecret_status_condition{
          job=~".*external-secrets.*",
          condition="Ready",
          status="False"
        }
      ) by (name, condition, status)
      == 1
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "ExternalSecretsProviderApiHighErrorRate"
    "annotations":
      "dashboard_url": "https://grafana.com/d/eso-overview-skj2/eso-overview"
      "description": "More than 5% of API calls to provider {{ $labels.provider }} failed the past 15m."
      "summary": "External Secrets Operator has a high provider API error rate."
    "expr": |
      (
        sum(
          increase(
            externalsecret_provider_api_calls_count{
              job=~".*external-secrets.*",
              status="error"
            }[15m]
          )
        ) by (provider)
        /
        sum(
          increase(
            externalsecret_provider_api_calls_count{
              job=~".*external-secrets.*"
            }[15m]
          )
        ) by (provider)
        * 100
      ) > 5
    "for": "5m"
    "labels":
      "severity": "warning"
